// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:balun/models/leagues/league/league.dart';
import 'package:balun/models/teams/team/team.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LeagueAdapter());
    registerAdapter(TeamAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LeagueAdapter());
    registerAdapter(TeamAdapter());
  }
}
