// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:balun/models/leagues/league/league.dart';
import 'package:balun/models/matches/favorite_match.dart';
import 'package:balun/models/notification/notification_fixture.dart';
import 'package:balun/models/notification/notification_settings.dart';
import 'package:balun/models/teams/team/team.dart';
import 'package:balun/models/theme/theme_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BalunThemeEnumAdapter());
    registerAdapter(ThemeModelAdapter());
    registerAdapter(LeagueAdapter());
    registerAdapter(TeamAdapter());
    registerAdapter(FavoriteMatchAdapter());
    registerAdapter(NotificationSettingsAdapter());
    registerAdapter(NotificationFixtureAdapter());
  }
}
